kind: Service
apiVersion: v1
metadata:
  name: saying-generator
spec:
  selector:
    app: saying-generator
    tier: backend
  ports:
    - protocol: TCP
      port: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saying-generator
spec:
  selector:
    matchLabels:
      app: saying-generator
      tier: backend
  template:
    metadata:
      labels:
        app: saying-generator
        tier: backend
    spec:
      containers:
        - name: saying-generator
          image: amberlight303/saying-generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091